### ISSUE TITLE
Integrate argent web wallet - new version

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#119]
**Description**
---
Integrate new version of argent web wallet

**Acceptance Criteria**
---
- [ ] Add new version of argent web wallet in current version of Dapp (3525)
- [ ] Give a Feedback to Argent X : organised a call if needed

**Comment by schwepps** [comment]
Connectors for webwallet:
 * https://web.dev.argent47.net -> goerli-alpha-2
 * https://web.hydrogen.argent47.net -> goerli-alpha
 * https://web.staging.argent47.net -> mainnet-alpha
 * https://web.argent.xyz -> mainnet-alpha
