### ISSUE TITLE
Farming Index Data Design

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#14]
**Description**
---
Establish data needed form `Farming page Index` and define data types needed (off-chain & on-chain). 

**Acceptance Criteria**
---

- [ ] A Table containing the list of Data needed for this Dapp page. 
- [ ] For each Data, specify the type, and if off-chain or on-chain

**Comment by schwepps** [comment]
Done in https://github.com/Carbonable/carbonable-starknet/issues/120
