### ISSUE TITLE
Change starknet logo

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-dapp#143]
change current starknet logo on the menu of the dapp by the following one

(request from Starknet themselves)

![Starknet single color-linear-black-on dark BG.svg](https://images.zenhubusercontent.com/646caae3ccc4c7933e320ada/6201cdc5-eb8f-4789-8088-f49588e91763)

**Comment by schwepps** [comment]
Done on mainnet. 
To do on testnet
