### ISSUE TITLE
CORS issue with dMRV images

### ISSUE THREAD

**Issue by schwepps** [Carbonable/carbonable-dapp#148]
**Describe the bug**
---
Sometimes there is a CORS issue when trying to fetch the dMRV images from the backend.

**To Reproduce**
---

- Display dMRV on Sea Starktest

**Behavior**
---
**Expected behavior**
The image is always displayed

**Actual behavior**
CORS issue, the overlay is not displayed

**Frequency**:
Most of the time

**Comment by schwepps** [comment]
It can't be fixed from the front end.
See: https://github.com/mapbox/mapbox-gl-js/issues/2171

It's a server issue.

**Comment by Bal7hazar** [comment]
I added CORS management in the server code

**Comment by schwepps** [comment]
Closing the issue, as it's working on testnet:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzhYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b63064f94666d72c31d23e804989e049c0c3013d/99983.png)
