### ISSUE TITLE
[Funding] Funding UX/UI

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#150]
**Description**
---
Implement new funding UX/UI based on the [Figma](https://www.figma.com/file/TxyvqO53GlCiTaJOE26AwM/dApp?type=design&node-id=4957-253246&mode=design&t=PSiKbyl6eLDfX7rC-0)

**Acceptance Criteria**
---

- [ ] Review UI
- [ ] Add leaderboard info

**Comment by schwepps** [comment]
Re-opening issue because it's linked to my PR.
I'll update title and description.

**Comment by schwepps** [comment]
I will also upgrade straknet-react version as part of this story

**Comment by schwepps** [comment]
Closed by #194
