### ISSUE TITLE
Project Data Design

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#18]
**Description**
---
Establish data needed form `Project page` and define data types needed (off-chain & on-chain). 

**Acceptance Criteria**
---

- [ ] A Table containing the list of Data needed for this Dapp page. 
- [ ] For each Data, specify the type, and if off-chain or on-chain

| Data | Location |Comment|
| --- | --- | --- |
|whitelistedSaleOpen|on-chain|From minter contract|
|publicSaleOpen|on-chain|From minter contract|
|soldout|on-chain|From minter contract|
|projectNftAddress|on-chain|From minter contract|
|paymentTokenAddress|on-chain|From minter contract|
|maxSupplyForMint|on-chain|From minter contract. Use to calculate the supplyLeft during a sale|
|unitPrice|on-chain|From minter contract. Use to calculate the priceToDisplay|
|projectTotalSupply|on-chain|From project contract. Use to calculate the supplyLeft during a sale|
|paymentTokenDecimals|on-chain|From payment token contract. Use to calculate the priceToDisplay|
|paymentTokenSymbol|on-chain|From payment token contract|
|saleIsOpen|calculated|whitelistedSaleOpen or publicSaleOpen|
|supplyLeft|calculated|maxSupplyForMint - projectTotalSupply|
|priceToDisplay|calculated|unitPrice / 10^paymentTokenDecimals|

**Comment by schwepps** [comment]
@cloudvenger @Bal7hazar @tekkac do you agree?

**Comment by tekkac** [comment]
Do we need to add off-chain data relevant to the specific project ? e.g., total carbon credits, carbon credit curve, location, name of project, etc ?

**Comment by schwepps** [comment]
I think we will need it later if we need to add filters for example.
But currently we don't (not for milestone 0.1 at least)
