### ISSUE TITLE
Leaderboard -dApp- Personal Goals

### ISSUE THREAD

**Issue by Khyati729** [Carbonable/carbonable-dapp#182]
**Description**
---
As Carbonable I want to showcase the personal goals to the connected user
In order to incentivize the user to take action on the Carbonable dapp

**Additional context**
---
This functionality can be displayed only when the User is connected.

Implementation & Design agreed on:
Figma
https://www.figma.com/file/TxyvqO53GlCiTaJOE26AwM/dApp?type=design&node-id=5297-56151&mode=design&t=hCUjQl00CidA9x58-0

Notion:
https://www.notion.so/carbonable/Users-LeaderBoard-Gamification-7a42afb6bbe74a9c8173f8907cc4bc46

**Acceptance Criteria**
---
User can find the following information on the Leaderboard page
- [ ] Personal Progress title 
- [ ] i Button over the Personal Progress - Text to be displayed in the tooltip when the user hovers over it <ToDo: Add Text>(TBD)
- [ ] **Total number of Points** earned by the User
- [ ]  **Discover Actions** Button should lead to a Medium Article with hook to a point where one can understand how to earn points

**Comment by schwepps** [comment]
Changing the estimate to 2 as is simplified in MVP.
