### ISSUE TITLE
Leaderboard -dApp- Share your score Button

### ISSUE THREAD

**Issue by Khyati729** [Carbonable/carbonable-dapp#184]
**Description**
---
As Carbonable I want the user to be able to showcase its personal achievements on the social media platforms
In order to incentivize the user for the points they have earned at Carbonable and also to spread awareness regarding Carbonable and its point system.

**Additional context**
---
This functionality can be displayed only when the User is connected.
When not connected, user should be prompted to connect their wallet.
<img width="480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHd3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37d9da03f47c5278ba02f814535de2add2e3c1e9/image.png" alt="image.png" />

Implementation & Design agreed on:
Figma
https://www.figma.com/file/TxyvqO53GlCiTaJOE26AwM/dApp?type=design&node-id=5297-56151&mode=design&t=hCUjQl00CidA9x58-0

Notion:
https://www.notion.so/carbonable/Users-LeaderBoard-Gamification-7a42afb6bbe74a9c8173f8907cc4bc46

**Acceptance Criteria**
---
User can perform the following action
- [ ]  Click the **Share** button and be able to post about its achievement.
- [ ]  Message to be displayed when someone clicks Share for SEO ans social media sharing < text > (TBD)
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDB3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--635d321114f8a7798d432155ba3bfeedca3fed36/image.png" alt="image.png" />

**Comment by schwepps** [comment]
@Khyati729 can you please provide me the expected text to display on social?

**Comment by schwepps** [comment]
Remaining: 
- Add SEO metadata with picture
- Add correct text to share
