### ISSUE TITLE
Missing / Bug Notification & Refresh in Dapp in Production

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#188]
**Describe the bug**
---
Context : Conversion Manjarisoa NFTs into SFT
After using button "Migration Assets" on Manjarisoa Bronze, I was able to do the conversion.
Everything was good on-chain (her the transaction : https://starkscan.co/tx/0x033b5815c6675d2ea8f2d62084225d8a2a40d85b12ca1ef849e420402738465a)
Her the SFT : https://starkscan.co/nft/0x0516d0acb6341dcc567e85dc90c8f64e0c33d3daba0a310157d6bba0656c8769/155

**Behavior**
---
**Expected behavior**
- Notification on the Dapp after transaction executed
- Refresh of the Dapp afetr an amount of time

**Actual behavior**
- No Notification on the Dapp
- No refresh of the Dapp
- Needed to be manually refresh after 1 min to have the new Manjarisoa SVG in SFT assets

**Screenshots**

<img width="1426" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3J3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fdade7a8311084261ebada3f9f8a58bf62ec0dc/After_Migration.PNG" alt="After_Migration.PNG" />
<img width="1457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3Z3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01d43f9c220a62de8ea524857e82dbb457d5e541/After_refresh_Migration.PNG" alt="After_refresh_Migration.PNG" />

**Comment by schwepps** [comment]
The notifications are indeed not triggered and the whole refresh system is based on the notifications calling the last status on the blockchain.
Need to investigate why the dapp doesn't receive the transaction hash after validation in the wallet which is the trigger of everything else.
