### ISSUE TITLE
 AVNU SDK- Onchain Activity

### ISSUE THREAD

**Issue by Khyati729** [Carbonable/carbonable-dapp#192]
**Description**
---
As Carbonable I want to be able to handle a multi currency buying in the dapp using AVNU SDK in order to provide multiple payment methods to the customers.

**Acceptance Criteria**
---
SDK Onchain Activities 
- [ ] Build Call Data using quote id 
 Execute multicall
- [ ] Approve spending token for swap
- [ ] Swap to USDC
- [ ] Approve minter to spent USDC
- [ ] Mint shares

**Comment by schwepps** [comment]
@Khyati729 build call is part of #193
