### ISSUE TITLE
 AVNU SDK- Offchain Activity

### ISSUE THREAD

**Issue by Khyati729** [Carbonable/carbonable-dapp#193]
**Description**
---
As Carbonable I want to be able to handle a multi currency buying in the dapp using AVNU SDK in order to provide multiple payment methods to the customers.

**Acceptance Criteria**
---
SDK Offchain Activities
- [ ] Get quotes to display info to user 
- [ ] Build call data
- [ ] Choose currency 
- [ ] Display minimum shares received

**Comment by Khyati729** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Tech-Team-workspace-64527a8c74b9f900123e10f6/issues/Carbonable/carbonable-dapp/193?planning-poker) with Zenhub @schwepps

**Comment by schwepps** [comment]
@Khyati729 the choose currency and the display minimum shares received will be part of #194.
In this story, the scope of this story is to
- Get a quote from a token available on goerli to USDC using: https://starknet.api.avnu.fi/swap/v1/quotes
- Build the calldata using https://starknet.api.avnu.fi/swap/v1/build for the swap to be done in #192
