### ISSUE TITLE
Change launchpad header to showcase next project

### ISSUE THREAD

**Issue by schwepps** [Carbonable/carbonable-dapp#196]
### Description
As Carbonable
I want to advertise about the next sale
In order to allow funders to join the presale

### Acceptance criteria

- [ ] Custom header with next project info
- [ ] Link to form

**Comment by G2CARBZ** [comment]
Link to the design / Figma

https://www.figma.com/file/TxyvqO53GlCiTaJOE26AwM/dApp?type=design&node-id=144%3A7290&mode=design&t=Hjz6ZvMm1pvKUNpN-1

<img width="671" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelZTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fefefcb4d674b80391246c4e5a1fe59820bb59ea/image.png" alt="image.png" />

And the background image here
<img width="1200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelpTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66721c1c8113ec3356c615dc250d414211a4fdc0/52633053_2187678071560991_23696945184768000_n.jpeg" alt="52633053_2187678071560991_23696945184768000_n.jpeg" />
