### ISSUE TITLE
 dApp - Changes to Checkout Page (Multi currency)

### ISSUE THREAD

**Issue by Khyati729** [Carbonable/carbonable-dapp#197]
**Description**
---
As Carbonable I want the user to be able to see Stark currency along with USDC 
In order to provide the user with an opportunity to be able to fund their projects with multicurrency options. 

**Additional context**
---
Image:
<img width="1265" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejVUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b9919e27bb101a08ccc054000ea73cb91a8160a/image%20%283%29.png" alt="image (3).png" />

<img width="1265" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenRUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4280d29d0222e40d63c8b50f359dd0bbf6079a42/image%20%284%29.png" alt="image (4).png" />

**Acceptance Criteria**
---
User can find the following 2 screen after clicking on Buy Now from the Launchpad:
1 Checkout screen
- [ ] Header - Checkout
- [ ] Box with header - Currency
- [ ] Inside this box user should be able to see 2 options: USDC and STARK
- [ ] Stark Token should be highlighted to draw the attention of the consumer in the box heading
- [ ] Second Box with heading Payment Details
- [ ] User should be able to see a breakdown of conversion rate, network fees, point he/she will be earning along with any boosts here, followed by Total Price 
- [ ] Confirm Transaction option that helps in completing the purchase.
- [ ] SVG image should also be displayed on the checkout screen  

2 Confirmation Screen
- [ ] Header - Congrats, Purchase complete
- [ ] Box with a header of Payment Details 
- [ ] User should be able to see information like Quantity, Delivered to, Tx Id and in the end Total Cost here.
- [ ] "Go To Farming"option that helps in returning to the Farming Page

**Comment by schwepps** [comment]
Need to do 2 quotes each time:
1 to have conversion rate USDC/ETH or STRK
1 to have a quote to swap ETH ou STRK en USDC
