### ISSUE TITLE
Claim All - option for Farming

### ISSUE THREAD

**Issue by Khyati729** [Carbonable/carbonable-dapp#212]
Description
--------------------------
As Carbonable, I should be able to provide the users an option of **_Claim All_**
in order to provide the user an option to pool all the farm pools when claiming. 

Acceptance Criteria
------------------------------
- [ ] Implementation of **_Claim All_**

**Comment by schwepps** [comment]
To be efficient, @MartianGreed will need to develop a new api for this.
Moving this ticket back to backlog to be picked up next sprint.
@Khyati729 can you create a backend ticket to create an api that returns all the resale smart contract on which a wallet can claim?
