### ISSUE TITLE
Leaderboard - User friendly Board

### ISSUE THREAD

**Issue by Khyati729** [Carbonable/carbonable-dapp#220]
Description
--------------------------------
As Carbonable I should have a better display of information in the Action and Boosts category in the Leaderboard history 
inorder to have a user friendly board with clearer depiction of information that's easily comprehendible. 

Additional Information
------------------------------------
<img width="1160" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3JqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9946d0ef476a117cde74465dea9dfad5fab5dcbf/image.png" alt="image.png" />

Acceptance Criteria
------------------------------
- [ ] Better user friendly board

**Comment by MartianGreed** [comment]
For the moment boosts only apply to 2 kind of events and only take the following form : 

- Funding project : (each dollar to fund the project)
    - 500$ and more -> x1.5
    - 1000$ and more -> x2
    - 5000$ and more -> x3
- Funding Karathuru (which are the milestones boosts)
    - < 50k$ -> x3
    - < 150k$ -> x2
    - < 300k$ -> x1.5
    - < 500k$ -> x1.2
    - < 700k$ -> x1.1 

For actions :
- "amount_funded" -> actions ("minter:buy", "minter:airdrop", "migrator:migration") -> each $ = 1 points (plus boost mechanism above)
- "number_of_projects" -> for now each project = 200 points
- "early_adopter" -> funding banegas farm = 200 points, funding las delicias = 150 points, funding manjarisoa = 100 points
- "offseter" -> each tCO2 claimed to offset equals 100 points
- "resaler" -> each $ claimed to resale equals 1 point
