### ISSUE TITLE
Web Wallet connection Issue

### ISSUE THREAD

**Issue by Khyati729** [Carbonable/carbonable-dapp#221]
Description:
-----------------------
Issue with Argent  Web Wallet connection to Carbonable. 

Acceptance Criteria
-------------------------------
-[ ] Seamless connection of Carbonable with the Argent web wallet.

**Comment by raizo07** [comment]
Hello, I'll love to work on this if it's still open.

**Comment by schwepps** [comment]
Hey @raizo07, thanks for your interest. 
We are currently checking with Argent what the issue really is. I'll let you know if the issue is on our side.

**Comment by raizo07** [comment]
Alright then, thank you very much. I'll be looking forward to hearing from
you.
