### ISSUE TITLE
Leaderboard - Bug - Your Points section

### ISSUE THREAD

**Issue by Khyati729** [Carbonable/carbonable-dapp#229]
Description
------------------------------------
Observed Behavior:
When a user clicks on the details of some other persons account on Leaderboard, in the Highlight section of "YOUR POINTS", user sees the other persons total points without the wallet being connected

Ideal Behavior:
- [ ] Others points should not be displayed in "YOUR POINTS" section when clicking on someone's name on Leaderboard
- [ ] In the "YOUR POINTS" section, user should see a message 
  "Connect wallet to show your points"

**Comment by schwepps** [comment]
I have differentiate the "Your points" section of the leaderboard and the "Points" section of the user history detail.
I have also added starknetId on personal ranking.
You can now also click on your personal ranking to see your history?.
And I have added profile pictures from starknetID
