### ISSUE TITLE
Bonus Page : Carbonable Odyssey

### ISSUE THREAD

**Issue by rmzlb** [Carbonable/carbonable-dapp#30]
Hello Guys, soumission quick win du weekend :

idée : créer de l'activité onchain sur le testnet (goerli1) et catalyser la distribution des badge
solution : page Carbonable Odyssey / quest

- execution 80/20 que je peux dev le weekend prochain (on améliorera pas la suite si besoin)
- Draft UX attached 
- lien vers nos quest (crew3 ou autre par la suite / ex focus tree & starknetID)
- reutilisation de l'animation home pour ne rendre clickable que le premier badge
- Workaround : gestion des whitelist non pris en charge à date 

[Figma](https://www.figma.com/file/RZnJETQ2upXT6RzVGFplBt/Carbonable---Design-(Copy)?node-id=401%3A280&t=ulhyfn485CydX0e5-1

![Image](https://user-images.githubusercontent.com/25151724/204219174-cf2affe1-c313-4bf1-b1da-3b6b833c03ff.png)

)

**Comment by cloudvenger** [comment]
Waiting the PR Smart Contract : [Adding the possibility of minting tokens](https://github.com/Carbonable/carbonable-starknet/pull/117)
