### ISSUE TITLE
Whitelist sale process

### ISSUE THREAD

**Issue by schwepps** [Carbonable/carbonable-dapp#32]
**Description**
---

Store whitelist from https://bal7hazar.github.io/whitelist-starknet/ in database
Check if user is eligible when page loads and when user clicks on mint.
Lock max number of NFT to mint from whitelist.

**Acceptance Criteria**
---

- [ ] User can mint during whitelist sale only if he is on the whitelist and can mint up to the max allowed quantity.
- [ ] Whitelist can be update in the database

**Additional context**
---

**Comment by cloudvenger** [comment]
Review with @Bal7hazar
