### ISSUE TITLE
[Dapp] Farming Index page - Farming cycles - Countdown & Statuses

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-dapp#40]
**Description**
---
Design reference
https://www.figma.com/file/TxyvqO53GlCiTaJOE26AwM/dApp?node-id=0%3A1&t=a2NYxoXVVLR9uNCd-1

- Have the countdown linked to the farming cycles
- Have the locked/unlocked status linked to the farming cycles

**Acceptance Criteria**
---

- [ ] Add and describe Acceptance Criteria
- [ ] Add and describe Acceptance Criteria

**Additional context**
---

**Comment by schwepps** [comment]
Fix #1
