### ISSUE TITLE
Cannot buy multiple NFTs

### ISSUE THREAD

**Issue by tekkac** [Carbonable/carbonable-dapp#53]
**Describe the bug**
---
Buying multiple NFTs at once on Kenya fails with `Assertion Error`

**To Reproduce**
---
    [Step 1] Connect with wallet (any testnet)
    [Step 2] Increment the number of NFT to be bought and click `Buy now`
    [Step 3] Get `Assertion Error`when wallet estimates transaction success. 

**Behavior**
---
**Expected behavior**
Transaction goes through

**Actual behavior**
`Assertion Failed`

**Frequency**:
Always

**Additional context**
---
`Allow` (approve?) method called with wrong argument (price for 1 NFT instead of price for actual number of NFTs)

**Comment by Bal7hazar** [comment]
Additional test, it works correctly manually on contracts (testnet-1)
- Approve ETH spend using ETH contract
- Public buy 5 NFT using Minter contract

The Assertion Failed error, suggest me that it is not an error handled by our contracts (which is consistent with test results)
![image](https://user-images.githubusercontent.com/97087040/207577896-c707c8d0-8ad0-4668-820b-89e8651cca8a.png)

**Comment by schwepps** [comment]
@cloudvenger 
Fix with #51

**Comment by cloudvenger** [comment]
👍
