### ISSUE TITLE
Changing network leads to 404 error

### ISSUE THREAD

**Issue by tekkac** [Carbonable/carbonable-dapp#54]
**Describe the bug**
---
Changing the network on a launchpad project mint page produces to 404 Error. It seems the route isn't changed.

**To Reproduce**
---
    [Step 1] Connect wallet and go to launchpad project
    [Step 2] Change network
    [Step 3] 404 error

**Behavior**
---
**Expected behavior**

Route is changed to testnet specific project page

**Actual behavior**
Same URL on network change procudes 404.

**Frequency**:
Always

**Comment by schwepps** [comment]
@cloudvenger won'f fix
Each projet has its own URL.
When you switch network, the current URL doesn't exist for the new network.

The 404 page can lead you to the launchpad to see the available projects on the selected network.

**Comment by cloudvenger** [comment]
Agreed for me 👍 

I changed it from bug to feature and give it to @G2CARBZ to define the UX/UI we want when we are an error of this type to manage and present to the user.

**Comment by schwepps** [comment]
Fix #77
