### ISSUE TITLE
Launch the Braavos wallet to mint when I log in with the Argent X wallet

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#55]
**Describe the bug**
---
When I log in with my Argent X wallet on the Dapp, then I want to buy an NFT of a project, the frontend opens my Braavos wallet instead of the Argent X wallet to mint. 

**Important**: However, this does not happen when I connect my wallet Argent X at the time I am on the project page I want to mint. This only happens when my wallet is connected to the front page, the Project Index page. 

**To Reproduce**
---
    [Step 1] I log in with my Argent X wallet on the Project index page,
    [Step 2] I click on a project and I arrive on its page.
    [Step 3] I try to buy an NFT of the project, the frontend opens my Braavos wallet instead of the Argent X wallet to pay. 

**Behavior**
---
**Expected behavior**
When I want to pay/mint, the frontend asks me to use the wallet I'm connected with. 

**Frequency**:
Each time on the testnet-2

**Comment by schwepps** [comment]
@cloudvenger I can't reproduce in dev so far.
Let's try again when a version will be deploy on fly.

**Comment by cloudvenger** [comment]
The same for me, I can not reproduce on the new dev. 

I close this bug and we reopen it if he comes back

**Comment by rmzlb** [comment]
![CleanShot 2022-12-15 at 17 46 25](https://user-images.githubusercontent.com/25151724/207920043-50fdc3c4-d4ea-484d-a1d6-894e51672103.png)

Réalisé après un premier mint reussi sur kenya j'ai selectionner un autre projet : uganda et bug 
quand je suis connecté avec argent
impossible de disconnect ou de mint ; et ça ouvre bravos par défaut

**Comment by schwepps** [comment]
Fix #1 
We now have a connection popup when multiple wallet
